POST http://127.0.0.1:3000/api/auth/registro
Accept: application/json
Content-Type: application/json

{
  "email": "admin2@mail.com",
  "password": "admin54321",
  "username":"admin"
}

### LOGIN

POST http://127.0.0.1:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin2@mail.com",
  "password": "admin54321"  
}


### Perfil 

GET http://127.0.0.1:3000/api/auth/perfil
Accept: application/json
Content-Type: application/json
Authorization: Bearer token



